### import package

In [2]:
import numpy as np
import tensorflow.keras as tf

In [3]:
size_of_room = [[1.0], [2.0]]
price_per_room = [[300.0], [500.0]]

Xtrain = np.array(size_of_room, dtype = np.float32)           
Ytrain = np.array(price_per_room, dtype = np.float32)       


In [4]:
linear_model_layer = tf.layers.Dense(units = 1, activation = "linear")

In [5]:
try:
    w, b = linear_model_layer.get_weights()
    print(f"w is = {w} and b is = {b}")
except:
    print(f"w is = {[]} and b is = {0}")

w is = [] and b is = 0


In [6]:
input_feature = Xtrain[0].reshape(1, 1)

a1 = linear_model_layer(input_feature)
a1

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.05439174]], dtype=float32)>

In [7]:
w, b = linear_model_layer.get_weights()
print(f"w is = {w} and b is = {b}")

w is = [[0.05439174]] and b is = [0.]


In [8]:
for i in range(len(Xtrain)):
    input_feature_i = Xtrain[i].reshape(1, 1)
    a_i = linear_model_layer(input_feature_i)
    w, b = linear_model_layer.get_weights()
    print(f"w is = {w} and b is = {b}")
    

w is = [[0.05439174]] and b is = [0.]
w is = [[0.05439174]] and b is = [0.]


In [9]:
set_w = np.array([[200]])
set_b = np.array([100])

linear_model_layer.set_weights([set_w, set_b])

w, b = linear_model_layer.get_weights()
print(f"w is = {w} and b is = {b}")

w is = [[200.]] and b is = [100.]


In [10]:
a1 = linear_model_layer(input_feature)
print(a1)
alin = np.dot(set_w, input_feature) + set_b
print(alin)

tf.Tensor([[300.]], shape=(1, 1), dtype=float32)
[[300.]]


In [19]:
X_train = np.array([[0., 1., 2., 3., 4., 5.]])  # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype = np.float32).reshape(-1, 1)  # 2-D Matrix


In [28]:
def sigmoid(z):
    return 1 / (np.exp(-z) + 1)

def my_dense(a_in, W, b, g):
    
    units = W.shape[1]
    a_out = np.zeros(units)
    for j in range(units):               
        w = W[:, j]                                    
        z = np.dot(w, a_in) + b[j]         
        a_out[j] = g(z)  
              
    return a_out

def my_sequential(x, W1, b1, W2, b2):
    a1 = my_dense(x,  W1, b1, sigmoid)
    a2 = my_dense(a1, W2, b2, sigmoid)
    return(a2)   

def my_predict(X, W1, b1, W2, b2):
    m = X.shape[0]
    p = np.zeros((m, 1))
    for i in range(m):
        p[i, 0] = my_sequential(X[i], W1, b1, W2, b2)
    return(p)

In [29]:
W1_tmp = np.array( [[-8.93,  0.29, 12.9 ], [-0.1,  -7.32, 10.81]] )
b1_tmp = np.array( [-9.82, -9.28,  0.96] )
W2_tmp = np.array( [[-31.18], [-27.59], [-32.56]] )
b2_tmp = np.array( [15.41] )

norm_l = tf.layers.Normalization(axis=-1)

X_tst = np.array([[200,13.9], [200,17]])  
X_tstn = norm_l(X_tst)  
predictions = my_predict(X_tstn, W1_tmp, b1_tmp, W2_tmp, b2_tmp)
yhat = (predictions >= 0.5).astype(int)
print(f"decisions = \n{yhat}")

decisions = 
[[0]
 [0]]


C:\Users\sathi\AppData\Local\Temp\ipykernel_16264\3483333986.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / (np.exp(-z) + 1)
